from . import foco_category
from . import foco_app
from . import foco_site
from . import foco_policy
from . import foco_computer
from . import foco_usage
from . import foco_event
from . import foco_workday
from . import foco_command
from . import foco_capture
from . import foco_watch
from . import foco_mobile
from . import foco_settings
from . import foco_invitation
from . import foco_absence
from . import hr_employee
from . import res_config_settings
from . import res_users
